spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/face?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: face
    password: face